config/routes.rb
Adherent::Engine.routes.draw do
  
  

  
  

  get "allpayments/index"

  resources :coords
  resources :payments, :controller=>:allpayments


  resources :members do
    resource :coord
    resources :adhesions
    resources :payments
  end
  
  resources :payments do
    resources :reglements
  end

  root :to=>'members#index'
end

app/controllers/adherent/adhesions_controller.rb
# coding utf-8

require_dependency "adherent/application_controller"

module Adherent
  class AdhesionsController < ApplicationController
    before_filter :find_member
    
    def index
      @adhesions = @member.adhesions
      if @adhesions.empty?
        flash[:notice] = 'Pas encore d\'adhésion pour ce membre ; redirigé vers la création d\'une adhésion'
        redirect_to new_member_adhesion_url(@member)
      end
    end
  
    def edit
      @adhesion= @member.adhesions.find(params[:id])
    end
    
    # PUT /adhesions/1
    # PUT /adhesions/1.json
    def update
      @adhesion = @member.adhesions.find(params[:id])
  
      respond_to do |format|
        if @adhesion.update_attributes(adhesion_params)
          format.html { redirect_to member_adhesions_path(@member), notice: 'Adhésion mise à jour.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          
        end
      end
    end
  
    def new
      @adhesion = @member.next_adhesion
    end
    
    # POST /adhesions
    # POST /adhesions.json
    def create
      @adhesion = @member.adhesions.new(adhesion_params)
      unless @adhesion.valid?
        
        flash[:notice] = @adhesion.errors.messages
      end
      respond_to do |format|
        if @adhesion.save
          format.html { redirect_to member_adhesions_url(@member), notice: 'Adhésion créée' }
          format.json { render json: @adhesion, status: :created, location: @adhesion }
        else
          format.html { render action: "new" }
          format.json { render json: @adhesion.errors, status: :unprocessable_entity }
        end
      end
    end
  
  
    
    # DELETE /adhesion/1
    # DELETE /coords/1.json
    def destroy
      @adhesion = @member.adhesions.find(params[:id])
      @adhesion.destroy
  
      respond_to do |format|
        format.html { redirect_to member_adhesions_url(@member) }
        
      end
    end
    
    protected
    
    def find_member
      @member = @organism.members.find(params[:member_id])
    end
    
    private 
    
     # Never trust parameters from the scary internet, only allow the white list through.
    def adhesion_params
      params.require(:adhesion).permit(:from_date, :to_date, :amount)
    end
  end
end

app/controllers/adherent/allpayments_controller.rb
require_dependency "adherent/application_controller"

module Adherent
  
  # les routes vers payments sont traitées par ce controller quand elles ne sont
  # pas dépendantes d'un membre. 
  # Si elles sont dépendantes d'un membre, alors, le controller est 
  # PaymentsController. Voir le fichier routes.rb
  
  class AllpaymentsController < ApplicationController
    def index
      @payments = @organism.payments.includes(:member, [:reglements=>[:adhesion=>:member]])
    end
  end
end

app/controllers/adherent/application_controller.rb
# pour avoir les méthodes d'authenfication proposées par l'ApplicationController
# ainsi que la gestion des sessions et notamment la méthode find_organism
class Adherent::ApplicationController < ApplicationController
  
  before_filter :spec_organism 
  
  # met en forme une date au format dd-mmm-yyyy en retirant le point 
  # par exemple 13-nov-2013 (et non 13-nov.-2016), ceci pour pouvoir 
  # facilement inclure la date dans le nom d'un fichier
  def dashed_date(date)
    I18n.l(date, format:'%d-%b-%Y').gsub('.', '')
  end
  
  private
  
  # ne sert qu'à instancier @organism dans les tests
  def spec_organism
    if Rails.env == 'test'
      @organism ||= Organism.first
    end
    
  end
  
  
  
  
end

app/controllers/adherent/coords_controller.rb
# coding utf-8

require_dependency "adherent/application_controller"

module Adherent
  class CoordsController < ApplicationController
    
    before_filter :find_member, :except=>[:index] 
   
    # GET /coords/1
    # GET /coords/1.json
    def show
      @coord = @member.coord 
      unless @coord
        flash[:alert] = "Pas encore de coordonnées pour #{@member.to_s}"
        redirect_to new_member_coord_url(@member) and return
      end   
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @coord }
      end
    end
  
    # GET /coords/new
    # GET /coords/new.json
    def new
      @coord = @member.build_coord
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @coord }
      end
    end
  
    # GET /coords/1/edit
    def edit
      @coord = @member.coord
    end
  
    # POST /coords
    # POST /coords.json
    def create
      @coord = @member.build_coord(coord_params)
  
      respond_to do |format|
        if @coord.save
          format.html { redirect_to new_member_adhesion_url(@member), notice: 'Coordonnées enregistrées' }
          format.json { render json: @coord, status: :created, location: @coord }
        else
          format.html { render action: "new" }
          format.json { render json: @coord.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /coords/1
    # PUT /coords/1.json
    def update
      @coord = @member.coord
  
      respond_to do |format|
        if @coord.update_attributes(coord_params)
          format.html { redirect_to member_coord_path(@member), notice: 'Coordonnées mises à jour' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @coord.errors, status: :unprocessable_entity }
        end
      end
    end
  
    
    
    protected 
    
    def find_member
      @member = @organism.members.find(params[:member_id])
    end

    
    def coord_params
      params.require(:coord).permit(:address, :city, :gsm, :mail, :office, :references, :tel, :zip)
    end
  end
end

app/controllers/adherent/members_controller.rb
# coding utf-8

require_dependency "adherent/application_controller"

module Adherent
  class MembersController < ApplicationController
    
    
    before_filter :find_member, :except=>[:index, :create, :new]
    
    
    # GET /members
    # GET /members.json
    def index 
  
      respond_to do |format|
        format.html {@members = Adherent::Member.query_members(@organism) }
        # index.html.erb
        format.csv { send_data Adherent::Member.to_csv(@organism),
          :filename=>"#{@organism.title}-#{dashed_date(Date.today)}-Membres.csv"  } 
        
        format.xls { send_data Adherent::Member.to_xls(@organism),
          :filename=>"#{@organism.title}-#{dashed_date(Date.today)}-Membres.csv"  }
        format.json { render json:@members }
      end
    end
  
    # GET /members/1
    # GET /members/1.json
    def show
     
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json:@member }
      end
    end
  
    # GET /members/new
    # GET /members/new.json
    def new
      @member = @organism.members.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json:@member }
      end
    end
  
    # GET /members/1/edit
    def edit
      
    end
  
    # POST /members
    # POST /members.json
    def create
      @member = @organism.members.new(member_params)
  
      respond_to do |format|
        if @member.save
          format.html { redirect_to new_member_coord_url(@member.id), notice: 'Le membre a été créé ; Enregistrez maintenant les coordonnées' }
          format.json { render json: @member, status: :created, location: @member }
        else
          format.html { render action: "new" }
          format.json { render json:@member.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /members/1
    # PUT /members/1.json
    def update
     
  
      respond_to do |format|
        if @member.update_attributes(member_params)
          format.html { redirect_to @member, notice: 'Les données ont été mises à jour' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /members/1
    # DELETE /members/1.json
    def destroy
      @member.destroy
      respond_to do |format|
        format.html { redirect_to members_url }
        format.json { head :no_content }
      end
    end
    
    private 
    
    
    
    def find_member
      @member = @organism.members.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:birthdate, :forname, :name, :number)
    end
  end
end

app/controllers/adherent/payments_controller.rb
require_dependency "adherent/application_controller"

module Adherent
  class PaymentsController < ApplicationController 
    
    before_filter :find_member 
    
    def index
      @payments = @member.payments.includes(:reglements=>[:adhesion=>:member])
    end
    
    def show
      @payment = @member.payments.includes(:reglements=>[:adhesion=>:member]).find_by_id(params[:id])
    end
  
    def new
      @payment = @member.payments.new(date:guess_date, amount:@member.unpaid_amount)
    end
    
    def create
      @payment=@member.payments.new(payment_params)
      if @payment.save
        
        flash[:notice] = 'Le paiement a été enregistré' 
        redirect_to member_payments_path(@member)
      else
        render 'new'
      end
    end
    
    def edit
      @payment = @member.payments.find_by_id(params[:id])
    end
    
    def update
      @payment = @member.payments.find_by_id(params[:id])
      Rails.logger.debug payment_params
      Rails.logger.debug "payment #{@payment.inspect}"
      if @payment.update_attributes(payment_params)
        
        flash[:notice] = 'Le paiement a été modifié' 
        redirect_to member_payments_path(@member)
      else
        
        flash[:alert] = base_errors_messages(@payment)
        render 'edit'
      end
    end
    
       
    
    # DELETE /payment/1
    # DELETE /coords/1.json
    def destroy
      @payment = @member.payments.find(params[:id])
      if @payment.destroy
        flash[:notice] = 'Le paiement a été supprimé'
      else
        flash[:alert] = base_errors_messages(@payment)
      end
  
      respond_to do |format|
        format.html { redirect_to member_payments_url(@member) }
      end
    end
    
    
    protected
    
    
    
    def find_member
      @member = @organism.members.find(params[:member_id])
    end
    
    # cette méthode permet à l'application qui intègre le gem adhérent 
    # de passer un message d'erreur à ce controller en ajoutant 
    # une erreur sur :base.
    # 
    def base_errors_messages(pay)
      perm = pay.errors.messages[:base]
      Rails.logger.debug "Inspection de perm #{perm.inspect}"
      if perm
        perm.join('<br/>').html_safe
      else
        nil        
      end
    end
    
    # choisit la date, de préférence la date du jour, mais s'assure que la d
    # date est dans les limites autorisées par range_date (définie dans Organisme)
    def guess_date
      date = Date.today
      rd = @member.organism.range_date 
      date = rd.last if date > rd.last
      date = rd.first if date < rd.first
      date
    end
    
    private
    
    def payment_params
      params.require(:payment).permit(:amount, :date, :mode, :comment)
    end
  end
end

app/controllers/adherent/reglements_controller.rb
require_dependency "adherent/application_controller"

module Adherent
  class ReglementsController < ApplicationController
    
    # enegistrer un nouveau réglement est en fait créer une nouvelle imputation 
    # pour un paiement. 
    # Il est donc obligatoire d'avoir un paiement
    #
    def new
      @payment = Payment.find(params[:payment_id])
      @member = @payment.member
      @reglement = @payment.reglements.new(amount:@payment.non_impute)
      @unpaid_adhesions = @organism.adhesions.unpaid
    end
    
    # TODO voir pour faire les deux approches (succès et échec)
    def create
      @payment = Payment.find(params[:payment_id])
      @payment.imputation_on_adh(params[:reglement][:adhesion_id])
      redirect_to member_payments_path(@payment.member)
      
    end
    
    def show
      @payment = Payment.find(params[:payment_id])
      @reglement = @payment.reglements.find(params[:id])
    end
    
    
    
   # DELETE /reglement/1
    
    def destroy
      @payment = Payment.find(params[:payment_id])
      @reglement = @payment.reglements.find(params[:id])
      if @reglement.destroy
        flash[:notice] = 'Le reglement a été supprimé'
      else
        flash[:alert] = 'Le règlement n\'a pas pu être supprimé'
      end
  
      respond_to do |format|
        format.html { redirect_to member_payment_url(@payment.member, @payment) }
      end
    end
    
    private
    
    def reglement_params
      params.require(:reglement).permit(:amount, :payment_id)
    end
    
  
    
  end
end

app/helpers/adherent/adherents_helper.rb
module Adherent
  module AdherentsHelper
  end
end

app/helpers/adherent/adhesion_helper.rb
module Adherent
  module AdhesionHelper
    
    def amount_due(adhesion)
      adhesion.due
    end
  end
end

app/helpers/adherent/allpayments_helper.rb
module Adherent
  module AllpaymentsHelper
    
  end
end

app/helpers/adherent/application_helper.rb
module Adherent
  module ApplicationHelper
    
    
    def icon_to(icon_file, options={}, html_options={})
      raise ArgumentError unless icon_file
      title = alt = icon_file.split('.')[0].capitalize

      html_options[:title] ||=title
      html_options[:class] ||= 'icon_menu'
      # html_options[:tabindex]= "-1"
      img_path="adherent/icones/#{icon_file}"
      link_to image_tag(img_path, :alt=> alt), options, html_options
    end
    
    def icon_to_if(condition, icon_file, options={}, html_options={})
      raise ArgumentError unless icon_file
      title = alt = icon_file.split('.')[0].capitalize

      html_options[:title] ||=title
      html_options[:class] ||= 'icon_menu'
      # html_options[:tabindex]= "-1"
      img_path="adherent/icones/#{icon_file}"
      link_to_if condition, image_tag(img_path, :alt=> alt), options, html_options
    end
    
    # Pour transformer un montant selon le format numérique français avec deux décimales
    def virgule(montant)
      ActionController::Base.helpers.number_with_precision(montant, precision:2) rescue '0,00'
    end
    
    def two_decimals(montant)
      sprintf('%0.02f',montant) rescue  '0.00'
    end
    
        
    def icon_to_users
      icon_to 'users.png', members_path, title:'Liste des membres' 
    end
    
    def list_imputations(payment)
      content_tag(:ul) do
        payment.reglements.map do |r|
          content_tag(:li) do
            imputation_with_actions(payment, r)
          end
        end.join.html_safe
      end
    end
    
    def imputation_with_actions(pay, r)
      # on gère le cas où l'adhésion a disparu (car le membre a disparu)
      a = r.adhesion
      mem = a ? a.member : 'supprimée'
      html = ''
      html << "Adhésion #{mem} pour #{number_to_currency(r.amount, locale: :fr)}"
      html << "&nbsp;&nbsp;"
      html << "#{icon_to 'detail.png', payment_reglement_path(pay.id, r.id)}"
      html.html_safe
    end
    
    def non_impute(payment)
      payment.amount - payment.reglements.to_a.sum(&:amount)
    end
    
  end
end

app/helpers/adherent/coords_helper.rb
module Adherent
  module CoordsHelper
  end
end

app/helpers/adherent/members_helper.rb
module Adherent
  module MembersHelper
  end
end

app/helpers/adherent/payments_helper.rb
module Adherent
  module PaymentsHelper
    def min_date 
      @member.organism.range_date.first
    end
    
    def max_date
      @member.organism.range_date.last
    end
    
    # Cette méthode est utilisée pour l'édition du reçu sous forme de courrier
    # 
    # cas de figure : le payment correspond précisément à l'adhésion du membre
    # on fait une édition simple : pour votre cotisation du .... au ...
    # Le payment reprend plusieurs règlements 
    # TODO A voir, il peut y avoir des paiements partiels ou total
    def recu_cotisation(payment, member)
      rs = payment.reglements
      if rs.count == 1 && rs.first.try(:adhesion).try(:member) == member
        adh = rs.first.adhesion
        "votre adhésion pour la période #{du_au(adh.from_date, adh.to_date)}"
        
      elsif rs.size == 1
        # une seule adhésion mais pas pour lui
        adh = rs.first.adhesion
        "l'adhésion de #{coords(adh)} pour la période #{pour(adh)}"    
      else  
        # plusieurs adhésions
        str  = "les adhésions de :"
        rs.each do |r| 
          
          adh = r.adhesion
          
          str += " - #{coords(adh)} pour la période #{pour(adh)}"
          
        end
        
        str.html_safe
      end
      
    end
    
    protected 
    
    def du_au(from_date, to_date)
      "du #{from_date} au #{to_date}"
    end
    
    def coords(adh)
      if adh && m = adh.member
        "#{m.name} #{m.forname}"
      else
        'Effacé'
      end
    end
    
    def pour(adh)
      if adh
      "#{du_au(adh.from_date, adh.to_date)}"
      else
       'du ??? au ???' 
      end
    end
  end
end

app/helpers/adherent/reglements_helper.rb
module Adherent
  module ReglementsHelper
  end
end

app/views/adherent/payments/_form.html.haml
.panel-body#transfer
  = simple_form_for([@member, @payment]) do |f|
    =f.error_notification
    .form-inputs
      .row
        = f.input :date, wrapper_html:{class:'col-lg-2'},
          input_html:{value:@payment.date, 
            date_min:min_date,
            date_max:max_date},
          :as=>:date_picker 
        = f.input :comment, wrapper_html:{class:'col-lg-5'}, 
          hint:'Factultatif. Si rempli, sera utilisé pour le libéllé de l\'écriture en compta'
        = f.input :amount, wrapper_html:{class:'col-lg-2'},
          input_html:{value:two_decimals(@payment.amount)}, :as=>:french_decimal
        = f.input :mode, wrapper_html:{class:'col-lg-3'},
          :collection=>Adherent::MODES, prompt:'Choisissez'   
    .form-actions
      = f.button :submit, id: 'new_payement', class: "btn-primary col-lg-2 col-lg-offset-7"

app/views/adherent/payments/_payment.html.haml
%tr
  %td= payment.date
  %td.numeric= number_to_currency(payment.amount, locale: :fr)
  %td= payment.comment
  %td= payment.mode
  %td= list_imputations(payment)
  - pni = non_impute(payment)
  %td.numeric= number_to_currency pni, locale: :fr

  %td
    - if (pni != 0.0)
      = icon_to 'imputation.png', new_payment_reglement_path(payment), title: 'Imputer le solde sur une adhésion'
    = icon_to 'detail.png', member_payment_path(payment.member, payment)

app/views/adherent/payments/_receipt.html.haml
= content_for :to_print do

  %h1#print_title
    = @organism.title
  %h4 Association à but non lucratif de droit français 
  %h4#print_subtitle régie par la loi du 1er juillet 1901

  %p#print_objet 
    Objet : reçu de cotisation de 
    = "#{@member.forname} #{@member.name} "
  #print_text
    %p Cher adhérent,
    %p
      Nous avons bien reçu le règlement de votre cotisation et nous vous en remercions.
    %p 
      Par la présente, nous attestons 
      que vous avez dûment acquitté auprès de notre
      association un montant de 
      = number_with_precision(@payment.amount, precision:2)
      € pour
      = "#{recu_cotisation(@payment, @member)}."
      
    %p 
      Nous vous rappelons que la cotisation n’est pas soumise à la    
      TVA et qu’elle ne donne pas lieu à la délivrance d’une facture.
    %p
      Nous vous prions d’agréer, cher adhérent, nos sincères          
      salutations.
  %p#print_date Le #{I18n::l(Date.today, format:'%d %B %Y')}                              
  %p#print_signature Le trésorier
  

app/views/adherent/payments/edit.html.erb
<%= content_for :menu do %>

<%= icon_to 'payment.png', member_payments_path(@member) %>
<% end -%>

<div class="champ">
  <h3>Modification d'un paiement de <%=  @member.to_s %></h3>

<div class="inner-champ">

<%= render 'form' %>
</div>
</div>

app/views/adherent/payments/index.html.haml
= content_for :menu do
  = icon_to_users
  = icon_to 'money-plus.png', new_member_payment_path(@member), title:'Nouveau paiement'


.champ
  %h3 Historique des paiements reçus de #{@member.to_s} 
  
  %table.table.table-striped.table-bordered.table-condensed(cellpadding="0" cellspacing="0" border="0")
    %thead
      %tr
        %th Le
        %th Montant
        %th Commentaire
        %th Par
        %th Imputé sur 
        %th Reste à imputer
        %th Actions
    %tbody
      = render @payments

app/views/adherent/payments/new.html.haml
=content_for :menu do
  = icon_to 'payment.png', member_payments_path(@member) 
.champ
  %h3 Enregistrement d'un paiement de #{@member.to_s}
  .inner-champ
    = render 'form'

app/views/adherent/payments/show.html.haml
= content_for :menu do
  = icon_to 'payment.png', member_payments_path(@member), title:"Liste des paiements de #{@member.to_s}" 
  = icon_to 'money-plus.png', new_member_payment_path(@member), title:'Nouveau paiement'
  - if (non_impute(@payment) != 0.0)
    = icon_to 'imputation.png', new_payment_reglement_path(@payment), title: 'Imputer le solde sur une autre adhésion'
  %a.icon_menu{href:'#'}
    = image_tag("adherent/icones/printer.png", title:'Imprimer un reçu', 
      class:'icon_print')
  
  = icon_to 'modifier.png', edit_member_payment_path(@payment.member, @payment)
  = icon_to 'supprimer.png', [@member,@payment], method: :delete, data: {confirm: 'Etes vous sûr ?'}
  

.champ
  %h3 Détail d'un paiement

  .inner-champ
    %p
      %b Effectué par :
      = @member.to_s
    %p
      %b Le :
      = @payment.date
    %p
      %b Montant :
      = number_to_currency(@payment.amount, locale: :fr)
    %p
      %b Commentaire :
      = @payment.comment
    %p
      %b Par :
      = @payment.mode
    %p
      %b Imputé sur :
      = list_imputations(@payment)
    %p
      %b Reste à imputer :
      = number_to_currency non_impute(@payment), locale: :fr
  

= render 'receipt'
  
    